### ISSUE TITLE
Email after expiration?

### ISSUE THREAD

**Issue by aajahid** [strangerstudios/pmpro-extra-expiration-warning-emails#1]
Is it possible to send warning email after the expiration? As an example - send email after 1 month of membership expiration and then another after 2 month?

The code kind a self explaining. But as I'm not familiar with the pmpro db structure - its hard for me to build the query to get all the users who's membership expired 30 days ago. I think it would be very easy for you, right?

**Comment by strangerstudios** [comment]
That's an interesting use case. It wouldn't make sense to use this code exactly, but you could use it as a base and yeah just update the query and the email sent.

I'm seeing this issue really late, but if you are still interested in this and would like help, you can post to our member forums and we'll whip up the code for you. Link back to my comment here to remind us to follow up. Thanks.
