### ISSUE TITLE
Multiple Emails

### ISSUE THREAD

**Issue by drivenfaroff** [strangerstudios/pmpro-extra-expiration-warning-emails#11]
I'm running .3.3 of this plugin.

I commented out the 60 and 90 day emails but kept the 30 day one.

I myself and others are receiving an email almost every day starting at 1 month out form the expiration date.

Not sure if this is something still ongoing with "\* BUG: The SQL query to find expiring members was including some users who had already received an email." or something else.

**Comment by lok1728** [comment]
I'm experiencing the same issue. Expiring members are receiving emails every day. I've posted this issue in the forums as well and am awaiting a response. Expiring members are receiving emails every day and they're not really happy about it.

**Comment by eighty20results** [comment]
We have a fix in the works to address this issue.

**Comment by strangerstudios** [comment]
New update coming out today that addresses this. Closing this issue, but please open it again if you continue to have issues. Thanks for your patience.
