### ISSUE TITLE
ENHANCEMENT REQUEST: error log filling up with 'no bad record cleanup needed' notices

### ISSUE THREAD

**Issue by LMNTL** [strangerstudios/pmpro-extra-expiration-warning-emails#23]
When WP_DEBUG is on, the plugin logs "No bad record cleanup needed" every time a page is requested because `pmproeewe_cleanup` is hooked to `init`. Quickly drowns out anything else in the error log. Could hook `pmproeewe_cleanup` to `pmpro_cron_expiration_warnings` instead, like we do with `pmproeewe_extra_emails`:
https://github.com/strangerstudios/pmpro-extra-expiration-warning-emails/blob/dev/pmpro-extra-expiration-warning-emails.php#L15

Forum topic (mods only):
https://www.paidmembershipspro.com/forums/topic/bug-eewe-add-on-bad-record-cleanup-running-every-30-seconds/

**Comment by ideadude** [comment]
Another one is logging when emails are sent with (Fake) in front. We should only log that if specifically testing: https://github.com/strangerstudios/pmpro-extra-expiration-warning-emails/blob/dev/pmpro-extra-expiration-warning-emails.php#L246-L248

**Comment by aquiferweb** [comment]
Just encountered this filling up my error log today. Do we have a workaround yet?

**Comment by trackwell-mike** [comment]
Same!

```
 No bad record cleanup needed: 0.7.2
```

**Comment by michaelbeil** [comment]
As reported in ticket 428991 (**moderators only**):
>The pmpro-extra-expiration-warning-emails add-on is filling our debug.log file with “No bad record cleanup needed”. This was mentioned back in 2019 on Github [here](https://github.com/strangerstudios/pmpro-extra-expiration-warning-emails/issues/23). The line throwing this message is [here](https://github.com/strangerstudios/pmpro-extra-expiration-warning-emails/blob/dev/pmpro-extra-expiration-warning-emails.php#L289): 
>`error_log( "No bad record cleanup needed: {$cleanup}");`
 
>Is there a suggested resolution to this?

This is a feature request for our development team to look into, however, I do not have an ETA as to **when** or **if** this will be included in an update. In the meantime, you’ll need to manually remove the errors from your debug log.

**Comment by Rsmith-gs** [comment]
> This is a feature request for our development team to look into, however, I do not have an ETA as to when or if this will be included in an update. In the meantime, you’ll need to manually remove the errors from your debug log.

This is happening in my php error log as well. Over the course of about a month it has made my error log over 5GB in size making it very difficult to decipher what is actually going on and making it almost impossible for me to actually manually remove the errors without crashing my code editor application (some applications won't even open files of this size).

**Comment by aquiferweb** [comment]
Same here - debug.log is filling up with No bad record cleanup needed: 0.7.2 - making debugging very awkward. I can't tell where in the code this is being generated from - but I do have the extra expiration warning emails add-on.

**Comment by ipokkel** [comment]
Also reported in ticket  #512729
My debug log is filling up with “No bad record cleanup needed: 0.7.2,”

**Comment by andrewlimaza** [comment]
I've created a Pull Request that adds an additional constant to the WP_DEBUG logic specifically for Extra Expiration Emails you can merge/test this PR prematurely as needed. https://github.com/strangerstudios/pmpro-extra-expiration-warning-emails/pull/33
