### ISSUE TITLE
$expiring_soon empty array

### ISSUE THREAD

**Issue by sdrumev** [strangerstudios/pmpro-extra-expiration-warning-emails#6]
Hi guys,

Th $expiring_soon is always and empty array for me. I think it's because there isn't pmpro_expiration_notice_{$pmpro_email_days_before_expiration} meta key in my usermeta table. Is this supposed to be working for existing users or only new ones that have subscribed/purchased after the implementation of this plugin?

Thanks

**Comment by strangerstudios** [comment]
Thanks for the heads up. Should be fixed by this patch:
https://github.com/strangerstudios/pmpro-extra-expiration-warning-emails/pull/7

I'll work to get that pushed out in an update ASAP
